// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAa55Gd8ZHMVDBsd5ivvuiSNSdSRYGxZk',
    appId: '1:932258130343:web:1328e1926d0b0b5805ae82',
    messagingSenderId: '932258130343',
    projectId: 'smart-farm-b1182',
    authDomain: 'smart-farm-b1182.firebaseapp.com',
    storageBucket: 'smart-farm-b1182.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExqEFFOVDtvA9BylVkkZ9hcTQs-DJYhQ',
    appId: '1:932258130343:android:636b9e365c8b03b605ae82',
    messagingSenderId: '932258130343',
    projectId: 'smart-farm-b1182',
    storageBucket: 'smart-farm-b1182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAojl1pAMYEtV7Zj8u7ayIzffymqE1KzVs',
    appId: '1:932258130343:ios:42d048bc907779a805ae82',
    messagingSenderId: '932258130343',
    projectId: 'smart-farm-b1182',
    storageBucket: 'smart-farm-b1182.firebasestorage.app',
    iosBundleId: 'com.example.smartFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAojl1pAMYEtV7Zj8u7ayIzffymqE1KzVs',
    appId: '1:932258130343:ios:42d048bc907779a805ae82',
    messagingSenderId: '932258130343',
    projectId: 'smart-farm-b1182',
    storageBucket: 'smart-farm-b1182.firebasestorage.app',
    iosBundleId: 'com.example.smartFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAa55Gd8ZHMVDBsd5ivvuiSNSdSRYGxZk',
    appId: '1:932258130343:web:28937782b97d3ea705ae82',
    messagingSenderId: '932258130343',
    projectId: 'smart-farm-b1182',
    authDomain: 'smart-farm-b1182.firebaseapp.com',
    storageBucket: 'smart-farm-b1182.firebasestorage.app',
  );
}
